# CONSTANTS THAT ARE COMMON TO MULTIPLE SOURCE FILES
IMG_WIDTH = 400
IMG_HEIGHT = 400
IMG_PATCH_SIZE = 16
IMG_PATCH_STRIDE = 8

PATCHES_MEAN_PATH = "../objects/patches_mean"

# post processing
DICT_PATCH_SIZE = (5, 5)